import {
    app,
    BrowserWindow,
    HandlerDetails,
    ipcMain,
    Menu,
    shell,
    WindowOpenHandlerResponse,
} from "electron";
import { handleGetCanvasCourses } from "src/api/canvas/courses";
import { handleGetCanvasStudents } from "src/api/canvas/students";
import { handleGetAssignments, handleGetSubmission } from "./api/canvas/grades";
import { handleGetTopHatCourses } from "./api/top-hat/courses";
import {
    saveTopHatStorageState,
    refreshTopHatAuthKey,
    handleGetLibertyCredentials,
    handleSaveLibertyCredentials,
} from "./api/top-hat/base";
import {
    handleEditAttendance,
    handleGetAttendanceItems,
    handleGetAttendanceRecords,
} from "./api/top-hat/attendance";
import { handleGetTopHatStudents } from "./api/top-hat/students";
import {
    handleGetCanvasCredentials,
    handleSaveCanvasCredentials,
} from "./api/canvas/base";
import {
    handleGetIntegrations,
    handleSaveIntegration,
} from "./api/integrations";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// eslint-disable-next-line @typescript-eslint/no-require-imports
if (require("electron-squirrel-startup")) {
    app.quit();
}

const createWindow = (): void => {
    // Create the browser window.
    const mainWindow = new BrowserWindow({
        height: 600,
        width: 800,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
    });

    mainWindow.webContents.setWindowOpenHandler(
        ({ url }: HandlerDetails): WindowOpenHandlerResponse => {
            shell.openExternal(url);
            return { action: "deny" };
        },
    );

    const menu = Menu.buildFromTemplate([
        {
            label: "File",
            submenu: [
                {
                    label: "Settings",
                    click: async () => {
                        mainWindow.webContents.send("update-view", "settings");
                    },
                },
            ],
        },
        {
            label: "Auth",
            submenu: [
                {
                    label: "Update TopHat authenticated state",
                    click: async () => {
                        await saveTopHatStorageState();
                    },
                },
                {
                    label: "Update TopHat refresh token",
                    click: async () => {
                        await refreshTopHatAuthKey();
                    },
                },
            ],
        },
    ]);

    mainWindow.setMenu(menu);

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
    mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
    if (process.platform !== "darwin") {
        app.quit();
    }
});

app.on("activate", () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

ipcMain.handle("canvas:get-credentials", handleGetCanvasCredentials);
ipcMain.handle("canvas:save-credentials", handleSaveCanvasCredentials);
ipcMain.handle("canvas:get-courses", handleGetCanvasCourses);
ipcMain.handle("canvas:get-students", handleGetCanvasStudents);
ipcMain.handle("canvas:get-assignments", handleGetAssignments);
ipcMain.handle("canvas:get-submission", handleGetSubmission);

ipcMain.handle("liberty:get-credentials", handleGetLibertyCredentials);
ipcMain.handle("liberty:save-credentials", handleSaveLibertyCredentials);

ipcMain.handle("top-hat:get-courses", handleGetTopHatCourses);
ipcMain.handle("top-hat:get-students", handleGetTopHatStudents);
ipcMain.handle("top-hat:get-attendance-items", handleGetAttendanceItems);
ipcMain.handle("top-hat:get-attendance-records", handleGetAttendanceRecords);
ipcMain.handle("top-hat:edit-attendance", handleEditAttendance);

ipcMain.handle("integrations:get-integrations", handleGetIntegrations);
ipcMain.handle("integrations:save-integration", handleSaveIntegration);
