import { config } from "dotenv";
import path from "path";
import { app, BrowserWindow, ipcMain } from "electron";
import { CanvasCourse } from "src/hooks/courses";
import { CanvasStudent } from "./hooks/students";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
// eslint-disable-next-line @typescript-eslint/no-require-imports
if (require("electron-squirrel-startup")) {
    app.quit();
}

config({ path: path.resolve(__dirname, "../../.env") });
const apiUrl = process.env.CANVAS_API_URL;
const apiKey = process.env.CANVAS_API_KEY;

const createWindow = (): void => {
    // Create the browser window.
    const mainWindow = new BrowserWindow({
        height: 600,
        width: 800,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
    });

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
    if (process.platform !== "darwin") {
        app.quit();
    }
});

app.on("activate", () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

ipcMain.handle("canvas:get-courses", async (): Promise<CanvasCourse[]> => {
    if (!apiUrl || !apiKey) {
        throw new Error("Missing Canvas credentials.");
    }

    const response = await fetch(`${apiUrl}/api/v1/courses`, {
        headers: {
            Authorization: `Bearer ${apiKey}`,
        },
    });

    if (!response.ok) {
        throw new Error(
            `Canvas API error: ${response.status} ${response.statusText}`,
        );
    }

    return response.json();
});

ipcMain.handle(
    "canvas:get-students",
    async (_, courseId: number): Promise<CanvasStudent[]> => {
        if (!apiUrl || !apiKey) {
            throw new Error("Missing Canvas credentials.");
        }

        const endpoint = `${apiUrl}/api/v1/courses/${courseId}/users?enrollment_type=student`;

        console.log(endpoint);

        const response = await fetch(endpoint, {
            headers: {
                Authorization: `Bearer ${apiKey}`,
            },
        });

        if (!response.ok) {
            throw new Error(
                `Canvas API error: ${response.status} ${response.statusText}`,
            );
        }

        return response.json();
    },
);
